let spoonerisms = [
"If enough people say a crazy phrase it becomes a phrasy craze",
"Better a turducken than a duckturdin",
"Don't kid your parents, but parent your kids",
"That’s the way the crumble cooks",
"Smells tasty > tastes smelly",
"Max and Mitch mix and match",
"In case of stairs use fire", //- maddi
"Spherical mirrors are Miracle spheres",
"That’s not facial hair, that’s a hair facial",
"Why is it so dang bad to bang dad?",
"Passive aggressive or aggressively passive?",
"Beverly Cleary is cleverly beery",
"Better a drip coffee than a drippy cough",
"Do you hold cans with those cold hands?",
"Paul Smecker has a small pecker",
"Folk punk polka funk",
"Post-crunk Crust Punk",
"Pop corn cop porn",
"Mitch’s eyelids itches my lids",
"You're not some asshole, you're a wholesome ass",
"Qualuudes > Lewd quails",
"Better hard to get than get too hard",
"Is this video game playing hard to get, or just getting hard to play?",
"On the other hand, the shoe is on the other foot",
"Better four point 0 than 0 point four",
"Reverse psychology > ygolohcysp esreveR",
"Sweeney Dan > Steely Todd",
"Funky muck monkey fuck",
"You're pretty crazy… You're crazy pretty",
"I may have a drinking problem, but I don’t have a problem drinking!",
"Jelly beans > belly jeans",
"Farewell, Wellfare",
"Would you rather have a margarita pizza, or a pizza margarita?",
"Touchdown in douchetown",
"Homeless shelter, or shelterless home?",
"Coming of age, or aging of cum?",
"O(n)? N(o)",
"I can't see the view but I can view the sea",
"I’m hardly easy, but I'm easily hard",
"Keep on onning keep",
"There are Mountain Dews and Mountain Donts",
"Shanwows and shamwhats",
//"Piece of shit / Shit of peach / Sheesh a pit",

//Drew burns = bruce dern
]