let uwDailyList = [
".DS_Store",
"420.jpg",
"Hillary.jpg",
"Stars.jpg",
"aderall.jpg",
"aggression.jpg",
"apartment.jpg",
"bezos.jpg",
"big data.jpg",
"bikini.jpg",
"bird and bee.jpg",
"bob hasegawa.JPG",
"breathe.jpg",
"bring them to heel.jpg",
"budget.jpg",
"cary moon.jpg",
"cat.jpg",
"chronic pain.jpg",
"class.jpg",
"coddled.jpg",
"condon.jpg",
"cross.jpg",
"crowded uw.jpg",
"dragon.jpg",
"dropout.jpg",
"eating disorder.JPG",
"education.jpg",
"election feelings.jpg",
"environment.jpg",
"excel.jpg",
"feminist ad color 2.jpg",
"fish.jpg",
"frats.jpg",
"ghosts.jpg",
"good place.jpg",
"hanging.jpg",
"ice.jpg",
"jenny durkin.JPG",
"jessyn farrell.jpg",
"lawmaker.jpg",
"leaves.jpg",
"mimimum wage color.jpg",
"monkey.JPG",
"obamaKim.JPG",
"online activism.jpg",
"oxxxford.jpg",
"palace.jpg",
"pregnancy.jpg",
"primate.jpg",
"pumpkin.jpg",
"ratings.jpg",
"restroom.jpg",
"sex ed.jpg",
"shoes.JPG",
"social media.jpg",
"stem.jpg",
"stuff.JPG",
"summer.jpg",
"tech love bw.jpg",
"tech vs nature.jpg",
"thoughts.jpg",
"to the bone.jpg",
"trump.jpg",
"trumpers.jpg",
"vegetables.jpg",
"vets.jpg",
"women in stem 2.jpg"]