let miscellaneousList = [
"BusinessSpooner.jpeg",
"DennisChair.png",
"GarfunkelOates.png",
"Gary.jpg",
"Genders.png",
"OffallyGood!.jpeg",
"Severance.jpg",
"SovietMonopoly.jpeg",
"Suey.png",
"Teapots.png",
"TheActualBeachBoys.jpeg",
"ThiccSpaghetti.jpg",
"TrainParking.jpeg",
"WolfOfWallStreetVHS.jpeg"]