let paintingsList = [
"BottleAndGoblet.jpg",
"Chantarelle.jpg",
"Harding.jpeg",
"MaddieAndThePancakes.jpeg",
"Mango.jpeg",
"McKinley.JPG",
"Pomegranate.JPG",
"Renaissance.JPG",
"SelfPortrait.jpg",
"SkullPainting.JPG",
"Taft.JPG",
"TheodoreRoosevelt.JPG",
"Vulture.jpeg",
"WineAndOnion.jpg",
"Winston.jpeg"]