let oldPianoList = [
"Action Park Theme.m4a",
"Angry Gershwin.m4a",
"Bond Theme.m4a",
"Bond.m4a",
"Bouncy Classical.m4a",
"Child Death Lullabye.m4a",
"Choir Intro (Sadly Bad).m4a",
"Classic Songbook.m4a",
"Etude 4.m4a",
"Falling Noir.m4a",
"Foggy Polychords.m4a",
"Forgotten Escape.m4a",
"Freedom Party.m4a",
"Friend Death.m4a",
"Hymn to Nikkal.m4a",
"Inspiring Musical.m4a",
"Japanese Dream Journey.mp3",
"Nighttime Barnyard.mp3",
"Old Clockwork.m4a",
"Old Dissonance.m4a",
"Pee-Wee Romp.m4a",
"Russian Lullabye.m4a",
"Russian Organ.mp3",
"Scary Western.m4a",
"Seattle Birthday.m4a",
"Unalike Lover's Musical Number.m4a",
"Urban Beat.m4a",
"Wandering C.m4a",
"Western 20's.m4a",
"Western Mafia.m4a"]