let artTable = [
["***FILENAME", "***GROUP", "***ORDER", "***CYCLE", "***SHUFFLE", ],
["ArtCircle.jpeg", "miscellaneous", ],
["Artichoke.JPG", "drawings", ],
["BottleAndGoblet.jpeg", "paintings", ],
["BusinessSpooner.jpeg", "miscellaneous", ],
["Carson.jpeg", "drawings", ],
["ch1_1.png", "lifeOfPika", "2", ],
["ch1_2.png", "lifeOfPika", "3", ],
["ch1_3.png", "lifeOfPika", "4", ],
["ch1_4.png", "lifeOfPika", "5", ],
["ch2_1.png", "lifeOfPika", "6", ],
["ch2_2.png", "lifeOfPika", "7", ],
["ch2_3.png", "lifeOfPika", "8", ],
["ch2_4.png", "lifeOfPika", "9", ],
["ch3_1.png", "lifeOfPika", "10", ],
["ch3_2.png", "lifeOfPika", "11", ],
["ch3_3.png", "lifeOfPika", "12", ],
["ch3_4.png", "lifeOfPika", "13", ],
["ch3_5.png", "lifeOfPika", "14", ],
["ch4_1.png", "lifeOfPika", "15", ],
["ch4_2.png", "lifeOfPika", "16", ],
["ch4_3.png", "lifeOfPika", "17", ],
["ch4_4.png", "lifeOfPika", "18", ],
["ch4_5.png", "lifeOfPika", "19", ],
["ch5_1.png", "lifeOfPika", "20", ],
["ch5_2.png", "lifeOfPika", "21", ],
["ch5_3.png", "lifeOfPika", "22", ],
["ch5_4.png", "lifeOfPika", "23", ],
["ch6_1.png", "lifeOfPika", "24", ],
["ch6_2.png", "lifeOfPika", "25", ],
["ch6_3.png", "lifeOfPika", "26", ],
["ch6_4.png", "lifeOfPika", "27", ],
["ch6_5.png", "lifeOfPika", "28", ],
["ch7_1.png", "lifeOfPika", "29", ],
["ch7_2.png", "lifeOfPika", "30", ],
["ch7_3.png", "lifeOfPika", "31", ],
["ch7_4.png", "lifeOfPika", "32", ],
["ch8_1.png", "lifeOfPika", "33", ],
["ch8_2.png", "lifeOfPika", "34", ],
["ch8_3.png", "lifeOfPika", "35", ],
["ch8_4.png", "lifeOfPika", "36", ],
["ch8_5.png", "lifeOfPika", "37", ],
["Chantarelle.jpg", "paintings", ],
["CherryTree.jpg", "drawings", ],
["CindyAndAlex.JPG", "paintings", ],
["Cube.JPG", "paintings", ],
["Dark Room 2.PNG", "deadEnd", ],
["Dead End 3.png", "deadEnd", ],
["DennisChair.png", "miscellaneous", ],
["Dove.jpg", "drawings", ],
["Face.jpeg", "drawings", ],
["Fountain.jpg", "drawings", ],
["Front Yard 2.png", "deadEnd", ],
["GarfunkelOates.png", "miscellaneous", ],
["Gary.jpg", "miscellaneous", ],
["Genders.png", "miscellaneous", ],
["Ghosts.jpeg", "drawings", ],
["Goat.jpeg", "drawings", ],
["graveyard1.JPG", "deadEnd", ],
["Harding.jpeg", "paintings", ],
["Informatics.png", "drawings", ],
["Jion.jpeg", "drawings", ],
["Kim.jpeg", "paintings", ],
["Kitchen 7.PNG", "deadEnd", ],
["Leander.jpg", "drawings", ],
["Living Room 4.PNG", "deadEnd", ],
["Living Room Plant 1.PNG", "deadEnd", ],
["LivingRoom.jpeg", "drawings", ],
["Maddie1.jpeg", "drawings", ],
["Maddie2.jpeg", "drawings", ],
["MaddieAndThePancakes.jpeg", "paintings", ],
["Madhava.jpeg", "drawings", ],
["Mango.jpeg", "paintings", ],
["Maze.jpeg", "drawings", ],
["McKinley.JPG", "paintings", ],
["OffallyGood!.jpeg", "miscellaneous", ],
["Olliver.jpeg", "drawings", ],
["Overhead.PNG", "deadEnd", ],
["Parents.JPG", "drawings", ],
["Pomegranate.jpeg", "paintings", ],
["Popcorn.jpeg", "drawings", ],
["Popcorn.jpeg", "drawings", ],
["Prab.jpg", "drawings", ],
["Prohibitionist.jpeg", "paintings", ],
["Rabbit.PNG", "deadEnd", ],
["RainbowHead.jpg", "paintings", ],
["Renaissance.JPG", "paintings", ],
["Sanjay.JPG", "drawings", ],
["Screen Shot 2013-12-30 at 12.29.37 PM.png", "deadEnd", ],
["Screen Shot 2014-01-07 at 6.43.06 PM.png", "deadEnd", ],
["Screen Shot 2014-06-23 at 6.35.27 PM.png", "deadEnd", ],
["Screen Shot 2014-07-02 at 2.48.27 PM.png", "deadEnd", ],
["Screen Shot 2014-08-08 at 9.22.40 AM.png", "deadEnd", ],
["SelfPortrait.jpg", "paintings", ],
["Severance.jpg", "miscellaneous", ],
["Shed.png", "deadEnd", ],
["sidepath3.png", "deadEnd", ],
["Skull.JPG", "drawings", ],
["SkullPainting.JPG", "paintings", ],
["SovietMonopoly.jpeg", "miscellaneous", ],
["Street 1.png", "deadEnd", ],
["Suey.png", "miscellaneous", ],
["Sunflowers.JPG", "drawings", ],
["Sunland.jpeg", "drawings", ],
["Taft.JPG", "paintings", ],
["Teapots.png", "miscellaneous", ],
["Tessellation.jpg", "drawings", ],
["TheActualBeachBoys.jpeg", "miscellaneous", ],
["TheodoreRoosevelt.JPG", "paintings", ],
["ThiccSpaghetti.jpg", "miscellaneous", ],
["TitleScreen.jpg", "lifeOfPika", "1", ],
["TrainParking.jpeg", "miscellaneous", ],
["Vulture.jpeg", "paintings", ],
["Window.jpg", "drawings", ],
["WineAndOnion.jpeg", "paintings", ],
["Winston.jpeg", "paintings", ],
["WolfOfWallStreetVHS.jpeg", "miscellaneous", ],
["Yard 5.PNG", "deadEnd", ],
["BlueRoom.jpeg", "paintings", ],
["Guy.jpeg", "paintings", ],
["Trotsky.jpeg", "drawings", ],
["Waterbottle.jpeg", "drawings", ],
["HymnToNikkal.jpg", "miscellaneous", ],
["head.jpeg", "photography", ],
["nearDeath.jpeg", "photography", ],
["kidsDance.jpeg", "photography", ],
["carBranch.jpeg", "photography", ],
["plantWindow.jpeg", "photography", ],
["54golf.jpeg", "photography", ],
["rec.jpeg", "photography", ],
["linux.jpeg", "photography", ],
["poohAndMickey.jpeg", "photography", ],
["puzzlePieces.jpeg", "photography", ],
["angerDisgustFear.jpeg", "photography", ],
["whoGivesACrap.jpeg", "photography", ],
["horrifyin.jpeg", "photography", ],
["drHummus.jpeg", "photography", ],
["stopThat.jpeg", "photography", ],
["carseatHat.jpeg", "photography", ],
["mrBill.jpeg", "photography", ],
["okMall.jpeg", "photography", ],
["daTuba.jpeg", "photography", ],
["prime.jpeg", "photography", ],
["fish.jpeg", "photography", ],
["prettyTired.jpeg", "photography", ],
["greyWood.jpeg", "photography", ],
["durn.jpeg", "photography", ],
["5star.jpeg", "photography", ],
["roughRoad.jpeg", "photography", ],
["plantWindowBig.jpeg", "photography", ],
["catMarvel.jpeg", "photography", ],
["pleaseDucks.jpeg", "photography", ],
["tacoBell.jpeg", "photography", ],
["weAre40.jpeg", "photography", ],
["orangeJuiceAirport.jpeg", "photography", ],
["veggies.jpeg", "photography", ],
["unixError.jpeg", "photography", ],
["dogEar.jpeg", "photography", ],
["savage.jpeg", "photography", ],
["420lit.jpeg", "photography", ],
["boomers.jpeg", "photography", ],
["closed.jpeg", "photography", ],
["noNoNo.jpeg", "photography", ],
["bePretty.jpeg", "photography", ],
["cow.jpeg", "photography", ],
["blueTree.jpeg", "photography", ],
["earth.jpeg", "photography", ],
["ranch.jpeg", "photography", ],
["kek.jpeg", "photography", ],
["wow.jpeg", "photography", ],
["smirk.jpeg", "photography", ],
["boardwalk.jpeg", "photography", ],
["upperDoor.jpeg", "photography", ],
["rock.jpeg", "photography", ],
["intertubes.jpeg", "photography", ],
["special.jpeg", "photography", ],
["godBless.jpeg", "photography", ],
["wizard.jpeg", "photography", ],
["hot.jpeg", "photography", ],
["nothingOfValue.jpeg", "photography", ],
["f.jpeg", "photography", ],
["lacroix.jpeg", "photography", ],
["iveFallen.jpeg", "photography", ],
["questionMark.jpeg", "photography", ],
["ucsf.jpeg", "photography", ],
["subwayTouchscreen.jpeg", "photography", ],
["outBus.jpeg", "photography", ],
["god.jpeg", "photography", ],
["be.jpeg", "photography", ],
["nightmareMustEnd.jpeg", "photography", ],
["lostKitten.jpeg", "photography", ],
["shoulder.jpeg", "photography", ],
["greatSalmon.jpeg", "photography", ],
["chocolateFactoryBear.jpeg", "photography", ],
["bigDog.jpeg", "photography", ],
["dontLive.jpeg", "photography", ],
["menOof.jpeg", "photography", ],
["pizza.jpeg", "photography", ],
["ravennaInteriors.jpeg", "photography", ],
["0-list.js", "photography", ],
["stairs.jpeg", "photography", ],
["beMoreAutistic.jpeg", "photography", ],
["sexyLifeSaladOn.jpeg", "photography", ],
["zombies.jpeg", "photography", ],
["perms.jpeg", "photography", ],
["pokemons.jpeg", "photography", ],
["ghostbust.jpeg", "photography", ],
["treeCaution.jpeg", "photography", ],
["pain.jpeg", "photography", ],
["sheldon.jpeg", "photography", ],
["funCard.jpeg", "photography", ],
["constructionAccident.jpeg", "photography", ],
["gun.jpeg", "photography", ],
["essentialsOfModernPhysics.jpeg", "photography", ],
["gramma.jpeg", "photography", ],
["mysteryMachine.jpeg", "photography", ],
["crunchyNuss.jpeg", "photography", ],
["dogStickerCar.jpeg", "photography", ],
["sealedAir.jpeg", "photography", ],
["dab.jpeg", "photography", ],
["882O.jpeg", "photography", ],
["chipsOnGround.jpeg", "photography", ],
["clownsFragile.jpeg", "photography", ],
["catEyes.jpeg", "photography", ],
["whatever.jpeg", "photography", ],
["mattressRoof.jpeg", "photography", ],
["rudolph.jpeg", "photography", ],
["fisherman.jpeg", "photography", ],
["lightningMcQueen.jpeg", "photography", ],
["copCar.jpeg", "photography", ],
["warningCancer.jpeg", "photography", ],
["hummusVitality.jpeg", "photography", ],
["sayNoToDrugs.jpeg", "photography", ],
["lifeBook.jpeg", "photography", ],
["leo.jpeg", "photography", ],
["spaghetti.jpeg", "photography", ],
["beehive.jpeg", "photography", ],
["graveTree.jpeg", "photography", ],
["bodyWindow.jpeg", "photography", ],
["cfu.jpeg", "photography", ],
["noTennis.jpeg", "photography", ],
["suprome.JPG", "photography", ],
["ben.jpeg", "photography", ],
["akwer.jpeg", "photography", ],
["chairs.jpeg", "photography", ],
["lRonHubbardWay.jpeg", "photography", ],
["outrage.jpeg", "photography", ],
["dock.jpeg", "photography", ],
["skateboardDrink.jpeg", "photography", ],
["mannekin.jpeg", "photography", ],
["couchBurn.jpeg", "photography", ],
["whereAmI.jpeg", "photography", ],
["cleff.jpeg", "photography", ],
["toilets.jpeg", "photography", ],
["smileyBoiler.jpeg", "photography", ],
["meanWell.jpeg", "photography", ],
["nlog.jpeg", "photography", ],
["clock.jpeg", "photography", ],
["texasMan.jpeg", "photography", ],
["accountability.jpeg", "photography", ],
["geico.jpeg", "photography", ],
["carefullyBurn.jpeg", "photography", ],
["dogs.jpeg", "photography", ],
["catWindow2.jpeg", "photography", ],
["doritos.jpeg", "photography", ],
["highHeel.jpeg", "photography", ],
["madameWeb.jpeg", "photography", ],
["car.jpeg", "photography", ],
["love.jpeg", "photography", ],
["moth.jpeg", "photography", ],
["shoesBasketball.jpeg", "photography", ],
["goAway.jpeg", "photography", ],
["tshirt.jpeg", "photography", ],
["beGayDoCrime.jpeg", "photography", ],
["jeans.jpeg", "photography", ],
["elvis.jpeg", "photography", ],
["420.jpeg", "photography", ],
["bible.jpeg", "photography", ],
["squareDance.jpeg", "photography", ],
["pizzaMaker.jpeg", "photography", ],
["1910.jpeg", "photography", ],
["babyStore.jpeg", "photography", ],
["stopp.jpeg", "photography", ],
["veganDog.jpeg", "photography", ],
["thatDarnCat.jpeg", "photography", ],
["babyStroller.jpeg", "photography", ],
["youAreMomGayLol.jpeg", "photography", ],
["beCarefulOfYouHead.jpeg", "photography", ],
["yo.jpeg", "photography", ],
["freeMayo.jpeg", "photography", ],
["yoMama.jpeg", "photography", ],
["crowBatman.jpeg", "photography", ],
["justMarried.jpeg", "photography", ],
["screenAd.jpeg", "photography", ],
["happySpring.jpeg", "photography", ],
["neverGiveUpOffice.jpeg", "photography", ],
["catWindow3.jpeg", "photography", ],
["dad.jpeg", "photography", ],
["iDontKnow.jpeg", "photography", ],
["grapes.jpeg", "photography", ],
["lordOfTheDance.jpeg", "photography", ],
["hunkyGuacamole.jpeg", "photography", ],
["catWindow.jpeg", "photography", ],
["paintSteps.jpeg", "photography", ],
["gasMask.jpeg", "photography", ],
["daiTogether.jpeg", "photography", ],
["fandiniJames.jpeg", "photography", ],
["miguels.jpeg", "photography", ],
["hm.jpeg", "photography", ],
["noSeJuega.jpeg", "photography", ],
["whatYearWereYouBorn.jpeg", "photography", ],
["NaN.jpeg", "photography", ],
["kokane.jpeg", "photography", ],
["mickey.jpeg", "photography", ],
["doNotEnter.jpeg", "photography", ],
["gender.jpeg", "photography", ],
["zebraMural.jpeg", "photography", ],
["30million.jpeg", "photography", ],
["watchOutForPinching.jpeg", "photography", ],
["skibidi.jpeg", "photography", ],
["amazon.jpeg", "photography", ],
["best.jpeg", "photography", ],
["fileCabinet.jpeg", "photography", ],
["isolationRoom.jpeg", "photography", ],
["neighsHoarsely.jpeg", "photography", ],
["spyCar.jpeg", "photography", ],
["newMexico.jpeg", "photography", ],
["hammerAndSickle.jpeg", "photography", ],
["selectOne.jpeg", "photography", ],
["spicy.jpeg", "photography", ],
["beach.jpeg", "photography", ],
["beefBend.jpeg", "photography", ],
["cigarette.jpeg", "photography", ],
["sheetMusic.jpeg", "photography", ],
["christmasHouse.jpeg", "photography", ],
["mirror.jpeg", "photography", ],
["washingtonFederal.jpeg", "photography", ],
["criticallyAcclaimed.jpeg", "photography", ],
["tunnel.jpeg", "photography", ],
["flag.jpeg", "photography", ],
["youAreYourId.jpeg", "photography", ],
["macaroni.jpeg", "photography", ],
["bajaBlast.jpeg", "photography", ],
["jeffGoldblum.jpeg", "photography", ],
["chinaError.jpeg", "photography", ],
["endTheInternet.jpeg", "photography", ],
["asianMan.jpeg", "photography", ],
["boyButter.jpeg", "photography", ],
["doll.jpeg", "photography", ],
["id.jpeg", "photography", ],
["stillIRise.jpeg", "photography", ],
["phucDat.jpeg", "photography", ],
["goldToilet.jpeg", "photography", ],
["wig.jpeg", "photography", ],
["babyShower.jpeg", "photography", ],
["abortion.jpeg", "photography", ],
["catSign.jpeg", "photography", ],
["sauce.jpeg", "photography", ],
["window.jpeg", "photography", ],
["succ.jpeg", "photography", ],
["iAmAGhost Large.jpeg", "photography", ],
["leaveRockHere.jpeg", "photography", ],
["cigaretteHand.jpeg", "photography", ],
["no.jpeg", "photography", ],
["doNotRemove.jpeg", "photography", ],
["internet.jpeg", "photography", ],
["realEstate.jpeg", "photography", ],
["fearOfDyin.jpeg", "photography", ],
["openBooks.jpeg", "photography", ],
["zza.jpeg", "photography", ],
["fenceWindow.jpeg", "photography", ],
["loveFever.jpeg", "photography", ],
["trainNotFound.jpeg", "photography", ],
["stop.jpeg", "photography", ],
["djKhaled.jpeg", "photography", ],
["amazonHertz.jpeg", "photography", ],
["handSanitizer.jpeg", "photography", ],
["darkness.jpeg", "photography", ],
["eczema.jpeg", "photography", ],
["horseySauce.jpeg", "photography", ],
["whatIsThis.jpeg", "photography", ],
["taiwam.jpeg", "photography", ],
["rooster.jpeg", "photography", ],
["homeless.jpeg", "photography", ],
["carts.jpeg", "photography", ],
["handJob.jpeg", "photography", ],
["diddley.jpeg", "photography", ],
["observed.jpeg", "photography", ],
["playKitchen.jpeg", "photography", ],
["toiletGlow.jpeg", "photography", ],
["loisLane.jpeg", "photography", ],
["smile.jpeg", "photography", ],
["packagedWithPride.jpeg", "photography", ],
["asbestos.jpeg", "photography", ],
["qrCode.jpeg", "photography", ],
["children.jpeg", "photography", ],
["dull.jpeg", "photography", ],
["studyingKnowledge.jpeg", "photography", ],
["please.jpeg", "photography", ],
["crows.jpeg", "photography", ],
["sometimes.jpeg", "photography", ],
["iDontNow.jpeg", "photography", ],
["moisture.jpeg", "photography", ],
["crookedWindow.jpeg", "photography", ],
["subjectiveLevel.jpeg", "photography", ],
["1973.jpeg", "photography", ],
["spiderweb.jpeg", "photography", ],
["foreignBank.jpeg", "photography", ],
["receipt.jpeg", "photography", ],
["horse.jpeg", "photography", ],
["refinedChineseTea.jpeg", "photography", ],
["treeSign.jpeg", "photography", ],
["calciumOmg.jpeg", "photography", ],
["banoDeMujeres.jpeg", "photography", ],
["legend.jpeg", "photography", ],
["noodle.jpeg", "photography", ],
["footPlanter.jpeg", "photography", ],
["myBurrito.jpeg", "photography", ],
["drugsUrinal.jpeg", "photography", ],
["cocktails.jpeg", "photography", ],
["smileyBowl.jpeg", "photography", ],
["tires.jpeg", "photography", ],
["wangSteak.jpeg", "photography", ],
["catFence.jpeg", "photography", ],
["corona.jpeg", "photography", ],
["jaundice.jpeg", "photography", ],
["blank.jpeg", "photography", ],
["mom.jpeg", "photography", ],
["vag.jpeg", "photography", ],
["outletFaces.jpeg", "photography", ],
["kittens.jpeg", "photography", ],
["sad.jpeg", "photography", ],
["caution.jpeg", "photography", ],
["laws.jpeg", "photography", ],
["peppers.jpeg", "photography", ],
["forkDoor.jpeg", "photography", ],
["ass.jpeg", "photography", ],
["benjamind.jpeg", "photography", ],
["sandwich.jpeg", "photography", ],
["rainier.jpeg", "photography", ],
["arcadeError.jpeg", "photography", ],
["chubbyLilMermaid.jpeg", "photography", ],
["furryCar.jpeg", "photography", ],
["artKeys.jpeg", "photography", ],
["waffles.jpeg", "photography", ],
["deadEnd.jpeg", "photography", ],
["arning.jpeg", "photography", ],
["plantCar.jpeg", "photography", ],
["manRepair.jpeg", "photography", ],
["hey.jpeg", "photography", ],
["stress.jpeg", "photography", ],
["fresh.jpeg", "photography", ],
["fiveDays.jpeg", "photography", ],
["grammaBin.jpeg", "photography", ],
["hello.jpeg", "photography", ],
["pumpkinShake.jpeg", "photography", ],
["fallingMan.jpeg", "photography", ],
["crosswalk.jpeg", "photography", ],
["pavementJoint.jpeg", "photography", ],
["dontTrustJustAnyone.jpeg", "photography", ],
["squirrell.jpeg", "photography", ],
["powerade.jpeg", "photography", ],
["dumpsterPhoto.jpeg", "photography", ],
["shoeprint.jpeg", "photography", ],
["1stAve.jpeg", "photography", ],
["mice.jpeg", "photography", ],
["daddysDonuts.jpeg", "photography", ],
["nameDate.jpeg", "photography", ],
["celsiBen.jpeg", "photography", ],
["men.jpeg", "photography", ],
["duckGooseDuck.jpeg", "photography", ],
["pikachu.jpeg", "photography", ],
["maniac.jpeg", "photography", ],
["rabbitsRabbitsRabbits.jpeg", "photography", ],
["banoDeHombres.jpeg", "photography", ],
["plantBox.jpeg", "photography", ],
["gaitronics.jpeg", "photography", ],
["wetPuddy.jpg", "photography", ],
["shitCatan.jpeg", "photography", ],
["goodJobfa.jpeg", "photography", ],
["voteNo.jpeg", "photography", ],
["wedding.jpeg", "photography", ],
["ooof.jpeg", "photography", ],
["noTable.jpeg", "photography", ],
["pointNGo.jpeg", "photography", ],
["balloons.jpeg", "photography", ],
["plantTruck.jpeg", "photography", ],
["myBad.jpeg", "photography", ],
["jPopp.jpeg", "photography", ],
["body.jpeg", "photography", ],
["specialFeatures.jpeg", "photography", ],
["greatRegularFlavor.jpeg", "photography", ],
["iFoundYourPhone.jpeg", "photography", ],
["thumbsUpGlove.jpeg", "photography", ],
["burnoutPrevention.jpeg", "photography", ],
["outlet.jpeg", "photography", ],
["peeece.jpeg", "photography", ],
["wetCement.jpeg", "photography", ],
["trendingNews.jpeg", "photography", ],
["congratulations.jpeg", "photography", ],
["grub.jpeg", "photography", ],
["toiletLeaves.jpeg", "photography", ],
["noRules.jpeg", "photography", ],
["phuketThai.jpeg", "photography", ],
["baldEagle.jpeg", "photography", ],
["hamOnWheat.jpeg", "photography", ],
["dogPlant.jpeg", "photography", ],
["fakeMoney.jpeg", "photography", ],
["restart.jpeg", "photography", ],
["projecting.jpeg", "photography", ],
["towers.jpeg", "photography", ],
["sassy.jpeg", "photography", ],
["instagramMug.jpeg", "photography", ],
["jeffEpstein.jpeg", "photography", ],
["neverGiveUpBillboard.jpeg", "photography", ],
]