let artTable = [
["1111.jpeg", "photography", ],
["1234.jpeg", "photography", ],
["1910.jpeg", "photography", ],
["1973.jpeg", "photography", ],
["1stAve.jpeg", "photography", ],
["2008.jpeg", "photography", ],
["30million.jpeg", "photography", ],
["419.jpeg", "photography", ],
["420.jpeg", "photography", ],
["420.jpg", "uwDaily", ],
["420lit.jpeg", "photography", ],
["5%.jpeg", "photography", ],
["54golf.jpeg", "photography", ],
["5star.jpeg", "photography", ],
["69.jpeg", "photography", ],
["8820.jpeg", "photography", ],
["882O.jpeg", "photography", ],
["abbaGuy.jpeg", "doodles", ],
["abortion.jpeg", "photography", ],
["accountability.jpeg", "photography", ],
["aderall.jpg", "uwDaily", ],
["afroPoint.jpeg", "photography", ],
["aggression.jpg", "uwDaily", ],
["akwer.jpeg", "photography", ],
["alienPuppet.jpeg", "doodles", ],
["amazon.jpeg", "photography", ],
["amazonHertz.jpeg", "photography", ],
["angerDisgustFear.jpeg", "photography", ],
["apartment.jpg", "uwDaily", ],
["aPizzaADay.jpeg", "photography", ],
["appleJack.jpeg", "doodles", ],
["arcadeError.jpeg", "photography", ],
["armGuy.jpeg", "doodles", ],
["arning.jpeg", "photography", ],
["arrow.jpeg", "photography", ],
["Art Trail (Cropped).JPG", "paintings", ],
["ArtCircle.jpeg", "miscellaneous", ],
["Artichoke.JPG", "drawings", ],
["artKeys.jpeg", "photography", ],
["ArtLink.jpg", "miscellaneous", ],
["asbestos.jpeg", "photography", ],
["asianMan.jpeg", "photography", ],
["ass.jpeg", "photography", ],
["babyShower.jpeg", "photography", ],
["babyStore.jpeg", "photography", ],
["babyStroller.jpeg", "photography", ],
["bacon.jpeg", "photography", ],
["bagels.jpeg", "photography", ],
["bajaBlast.jpeg", "photography", ],
["baldEagle.jpeg", "photography", ],
["baldGlasses.jpeg", "photography", ],
["balloons.jpeg", "photography", ],
["bananaGround.jpeg", "photography", ],
["bananaLedge.jpeg", "photography", ],
["banoDeHombres.jpeg", "photography", ],
["banoDeMujeres.jpeg", "photography", ],
["be.jpeg", "photography", ],
["beach.jpeg", "photography", ],
["bean.jpeg", "photography", ],
["beCarefulOfYouHead.jpeg", "photography", ],
["beefBend.jpeg", "photography", ],
["beehive.jpeg", "photography", ],
["beGayDoCrime.jpeg", "photography", ],
["beJeep.jpeg", "photography", ],
["beMoreAutistic.jpeg", "photography", ],
["ben.jpeg", "photography", ],
["beNice.jpeg", "photography", ],
["benjamind.jpeg", "photography", ],
["bePretty.jpeg", "photography", ],
["best.jpeg", "photography", ],
["bezos.jpg", "uwDaily", ],
["bible.jpeg", "photography", ],
["bibleTree.jpeg", "photography", ],
["bidenHarris.jpeg", "photography", ],
["big data.jpg", "uwDaily", ],
["bigDog.jpeg", "photography", ],
["bikeRack.jpeg", "photography", ],
["bikini.jpg", "uwDaily", ],
["bird and bee.jpg", "uwDaily", ],
["blackberryTv.jpeg", "photography", ],
["blank.jpeg", "photography", ],
["blueMnMs.jpeg", "photography", ],
["BlueRoom.jpeg", "paintings", ],
["blueTree.jpeg", "photography", ],
["boardwalk.jpeg", "photography", ],
["bob hasegawa.JPG", "uwDaily", ],
["body.jpeg", "photography", ],
["bodyWindow.jpeg", "photography", ],
["boomers.jpeg", "photography", ],
["booneScholibo.jpeg", "photography", ],
["BottleAndGoblet.jpeg", "paintings", ],
["boyButter.jpeg", "photography", ],
["bratNote.jpeg", "photography", ],
["breathe.jpg", "uwDaily", ],
["bring them to heel.jpg", "uwDaily", ],
["brokenGlass.jpeg", "photography", ],
["Brule.jpeg", "miscellaneous", ],
["budget.jpg", "uwDaily", ],
["burnoutPrevention.jpeg", "photography", ],
["burrito.jpeg", "photography", ],
["BusinessSpooner.jpeg", "miscellaneous", ],
["busyToy.jpeg", "photography", ],
["buttermilk.jpeg", "photography", ],
["calciumOmg.jpeg", "photography", ],
["car.jpeg", "photography", ],
["carBranch.jpeg", "photography", ],
["cards.jpeg", "photography", ],
["carefullyBurn.jpeg", "photography", ],
["carPurple.jpeg", "photography", ],
["carseatHat.jpeg", "photography", ],
["carSmall.jpeg", "photography", ],
["Carson.jpeg", "drawings", ],
["carts.jpeg", "photography", ],
["cary moon.jpg", "uwDaily", ],
["cat.jpg", "uwDaily", ],
["catEyes.jpeg", "photography", ],
["catFence.jpeg", "photography", ],
["catFlap.jpeg", "photography", ],
["catMarvel.jpeg", "photography", ],
["catPlay.jpeg", "photography", ],
["catSign.jpeg", "photography", ],
["catWindow.jpeg", "photography", ],
["catWindow2.jpeg", "photography", ],
["catWindow3.jpeg", "photography", ],
["caution.jpeg", "photography", ],
["ccc555.jpeg", "photography", ],
["celci.jpeg", "photography", ],
["celsiBen.jpeg", "photography", ],
["Censorship.jpeg", "drawings", ],
["cfu.jpeg", "photography", ],
["ch1_1.png", "lifeOfPika", "2", ],
["ch1_2.png", "lifeOfPika", "3", ],
["ch1_3.png", "lifeOfPika", "4", ],
["ch1_4.png", "lifeOfPika", "5", ],
["ch2_1.png", "lifeOfPika", "6", ],
["ch2_2.png", "lifeOfPika", "7", ],
["ch2_3.png", "lifeOfPika", "8", ],
["ch2_4.png", "lifeOfPika", "9", ],
["ch3_1.png", "lifeOfPika", "10", ],
["ch3_2.png", "lifeOfPika", "11", ],
["ch3_3.png", "lifeOfPika", "12", ],
["ch3_4.png", "lifeOfPika", "13", ],
["ch3_5.png", "lifeOfPika", "14", ],
["ch4_1.png", "lifeOfPika", "15", ],
["ch4_2.png", "lifeOfPika", "16", ],
["ch4_3.png", "lifeOfPika", "17", ],
["ch4_4.png", "lifeOfPika", "18", ],
["ch4_5.png", "lifeOfPika", "19", ],
["ch5_1.png", "lifeOfPika", "20", ],
["ch5_2.png", "lifeOfPika", "21", ],
["ch5_3.png", "lifeOfPika", "22", ],
["ch5_4.png", "lifeOfPika", "23", ],
["ch6_1.png", "lifeOfPika", "24", ],
["ch6_2.png", "lifeOfPika", "25", ],
["ch6_3.png", "lifeOfPika", "26", ],
["ch6_4.png", "lifeOfPika", "27", ],
["ch6_5.png", "lifeOfPika", "28", ],
["ch7_1.png", "lifeOfPika", "29", ],
["ch7_2.png", "lifeOfPika", "30", ],
["ch7_3.png", "lifeOfPika", "31", ],
["ch7_4.png", "lifeOfPika", "32", ],
["ch8_1.png", "lifeOfPika", "33", ],
["ch8_2.png", "lifeOfPika", "34", ],
["ch8_3.png", "lifeOfPika", "35", ],
["ch8_4.png", "lifeOfPika", "36", ],
["ch8_5.png", "lifeOfPika", "37", ],
["chainlink.jpeg", "photography", ],
["chair.jpeg", "photography", ],
["chairs.jpeg", "photography", ],
["changeChannel.jpeg", "photography", ],
["Chantarelle.jpg", "paintings", ],
["chargeFastLiveMore.jpeg", "photography", ],
["CherryTree.jpg", "drawings", ],
["children.jpeg", "photography", ],
["chinaError.jpeg", "photography", ],
["chips.jpeg", "photography", ],
["chipsOnGround.jpeg", "photography", ],
["chocolateFactoryBear.jpeg", "photography", ],
["christmasHouse.jpeg", "photography", ],
["christmasLights.jpeg", "photography", ],
["chronic pain.jpg", "uwDaily", ],
["chs.jpg", "miscellaneous", ],
["chubbyLilMermaid.jpeg", "photography", ],
["cigarette.jpeg", "photography", ],
["cigaretteHand.jpeg", "photography", ],
["CindyAndAlex.JPG", "paintings", ],
["circuitBoard.jpeg", "photography", ],
["class.jpg", "uwDaily", ],
["cleff.jpeg", "photography", ],
["clock.jpeg", "photography", ],
["closed.jpeg", "photography", ],
["clown.jpeg", "photography", ],
["clownsFragile.jpeg", "photography", ],
["cocktails.jpeg", "photography", ],
["coddled.jpg", "uwDaily", ],
["colorBars.jpeg", "photography", ],
["condon.jpg", "uwDaily", ],
["coneTree.jpeg", "photography", ],
["congratulations.jpeg", "photography", ],
["constructionAccident.jpeg", "photography", ],
["copCar.jpeg", "photography", ],
["coreCollectiveLetters.jpeg", "photography", ],
["corona.jpeg", "photography", ],
["couchBurn.jpeg", "photography", ],
["cougar.jpeg", "photography", ],
["countryAf.jpeg", "photography", ],
["cow.jpeg", "photography", ],
["crab.jpeg", "photography", ],
["criticallyAcclaimed.jpeg", "photography", ],
["crookedWindow.jpeg", "photography", ],
["cross.jpg", "uwDaily", ],
["crosswalk.jpeg", "photography", ],
["crowBatman.jpeg", "photography", ],
["crowded uw.jpg", "uwDaily", ],
["crows.jpeg", "photography", ],
["crunchyNuss.jpeg", "photography", ],
["Cube.JPG", "paintings", ],
["dab.jpeg", "photography", ],
["dad.jpeg", "photography", ],
["daddysDonuts.jpeg", "photography", ],
["daiTogether.jpeg", "photography", ],
["Dark Room 2.PNG", "deadEnd", ],
["darkness.jpeg", "photography", ],
["daTuba.jpeg", "photography", ],
["Davis.jpeg", "drawings", ],
["Dead End 3.png", "deadEnd", ],
["deadEnd.jpeg", "photography", ],
["deafDog.jpeg", "photography", ],
["DennisChair.png", "miscellaneous", ],
["diddley.jpeg", "photography", ],
["digitalPerm.jpeg", "photography", ],
["dinosaurLight.jpeg", "photography", ],
["djKhaled.jpeg", "photography", ],
["dock.jpeg", "photography", ],
["dogCar.jpeg", "photography", ],
["dogCarWindow.jpeg", "photography", ],
["dogEar.jpeg", "photography", ],
["dogPlant.jpeg", "photography", ],
["dogRailing.jpeg", "photography", ],
["dogs.jpeg", "photography", ],
["dogStickerCar.jpeg", "photography", ],
["dogWalk.jpeg", "photography", ],
["doll.jpeg", "photography", ],
["dollHead.jpeg", "photography", ],
["doNotEnter.jpeg", "photography", ],
["doNotRemove.jpeg", "photography", ],
["dontLive.jpeg", "photography", ],
["dontTrustJustAnyone.jpeg", "photography", ],
["door.jpeg", "photography", ],
["doritos.jpeg", "photography", ],
["doSomething.jpeg", "photography", ],
["Dove.jpg", "drawings", ],
["dragon.jpg", "uwDaily", ],
["drHummus.jpeg", "photography", ],
["drinkBroken.jpeg", "photography", ],
["dropout.jpg", "uwDaily", ],
["drPhil.jpeg", "photography", ],
["drugsUrinal.jpeg", "photography", ],
["duckGooseDuck.jpeg", "photography", ],
["duh.jpeg", "photography", ],
["dull.jpeg", "photography", ],
["dumpsterPhoto.jpeg", "photography", ],
["durn.jpeg", "photography", ],
["earth.jpeg", "photography", ],
["eating disorder.JPG", "uwDaily", ],
["eczema.jpeg", "photography", ],
["education.jpg", "uwDaily", ],
["election feelings.jpg", "uwDaily", ],
["elvis.jpeg", "photography", ],
["endIsNye.jpeg", "photography", ],
["endOfTheLine.jpeg", "photography", ],
["endTheInternet.jpeg", "photography", ],
["environment.jpg", "uwDaily", ],
["essentialsOfModernPhysics.jpeg", "photography", ],
["excel.jpg", "uwDaily", ],
["exitNot.jpeg", "photography", ],
["expectDelays.jpeg", "photography", ],
["extraSouce.jpeg", "photography", ],
["eyes.jpeg", "photography", ],
["f.jpeg", "photography", ],
["Face.jpeg", "drawings", ],
["fakeMoney.jpeg", "photography", ],
["fallingMan.jpeg", "photography", ],
["fandiniJames.jpeg", "photography", ],
["fearOfDyin.jpeg", "photography", ],
["FeminineCollage.jpg", "miscellaneous", ],
["feminist ad color 2.jpg", "uwDaily", ],
["fence.jpeg", "photography", ],
["fenceBroken2.jpeg", "photography", ],
["fenceWindow.jpeg", "photography", ],
["fileCabinet.jpeg", "photography", ],
["firSt.jpeg", "photography", ],
["fish.jpeg", "photography", ],
["fish.jpg", "uwDaily", ],
["fisherman.jpeg", "photography", ],
["fiveDays.jpeg", "photography", ],
["fiveGuys.jpeg", "photography", ],
["flag.jpeg", "photography", ],
["flags.jpeg", "photography", ],
["fly.jpeg", "photography", ],
["footHands.jpeg", "photography", ],
["footPlanter.jpeg", "photography", ],
["foreignBank.jpeg", "photography", ],
["forkDoor.jpeg", "photography", ],
["Fountain.jpg", "drawings", ],
["Franz.jpeg", "drawings", ],
["frats.jpg", "uwDaily", ],
["freeMayo.jpeg", "photography", ],
["freePeople.jpeg", "photography", ],
["fresh.jpeg", "photography", ],
["Front Yard 2.png", "deadEnd", ],
["funCard.jpeg", "photography", ],
["furryCar.jpeg", "photography", ],
["gaitronics.jpeg", "photography", ],
["gardenMask.jpeg", "photography", ],
["GarfunkelOates.png", "miscellaneous", ],
["Gary.jpg", "miscellaneous", ],
["gasMask.jpeg", "photography", ],
["gatorade.jpeg", "photography", ],
["geico.jpeg", "photography", ],
["gender.jpeg", "photography", ],
["Genders.png", "miscellaneous", ],
["ghostbust.jpeg", "photography", ],
["Ghosts.jpeg", "drawings", ],
["ghosts.jpg", "uwDaily", ],
["glinda.jpeg", "photography", ],
["Goat.jpeg", "drawings", ],
["goAway.jpeg", "photography", ],
["god.jpeg", "photography", ],
["godBless 2.jpeg", "photography", ],
["godBless.jpeg", "photography", ],
["goldToilet.jpeg", "photography", ],
["good place.jpg", "uwDaily", ],
["goodFoodServedHere.jpeg", "photography", ],
["goodJobfa.jpeg", "photography", ],
["goodMorningGoodbye.jpeg", "photography", ],
["gootz.jpeg", "photography", ],
["graceTruth.jpeg", "photography", ],
["graffitiWeird.jpeg", "photography", ],
["gramma.jpeg", "photography", ],
["grammaBin.jpeg", "photography", ],
["grapes.jpeg", "photography", ],
["grapeSoda.jpeg", "photography", ],
["graveTree.jpeg", "photography", ],
["graveyard1.JPG", "deadEnd", ],
["greatRegularFlavor.jpeg", "photography", ],
["greatSalmon.jpeg", "photography", ],
["greyWood.jpeg", "photography", ],
["grub.jpeg", "photography", ],
["gun.jpeg", "photography", ],
["Guy.jpeg", "paintings", ],
["halloweenTruck.jpeg", "photography", ],
["hammerAndSickle.jpeg", "photography", ],
["hamOnWheat.jpeg", "photography", ],
["handJob.jpeg", "photography", ],
["handSanitizer.jpeg", "photography", ],
["hangers.jpeg", "photography", ],
["hanging.jpg", "uwDaily", ],
["happySpring.jpeg", "photography", ],
["Harding.jpeg", "paintings", ],
["head.jpeg", "photography", ],
["hello.jpeg", "photography", ],
["helloH9b.jpeg", "photography", ],
["hey.jpeg", "photography", ],
["hideFacesFromMemories.jpeg", "photography", ],
["highHeel.jpeg", "photography", ],
["Hillary.jpg", "uwDaily", ],
["hm.jpeg", "photography", ],
["hmm.jpeg", "photography", ],
["homeless.jpeg", "photography", ],
["horrifyin.jpeg", "photography", ],
["horse.jpeg", "photography", ],
["horseySauce.jpeg", "photography", ],
["hot.jpeg", "photography", ],
["hotSauce.jpeg", "photography", ],
["houseInHouse.jpeg", "photography", ],
["hummusVitality.jpeg", "photography", ],
["hunkyGuacamole.jpeg", "photography", ],
["HymnToNikkal.jpg", "miscellaneous", ],
["iAmAGhost.jpeg", "photography", ],
["ice.jpg", "uwDaily", ],
["id.jpeg", "photography", ],
["iDontKnow.jpeg", "photography", ],
["iDontNow.jpeg", "photography", ],
["iFoundYourPhone.jpeg", "photography", ],
["Informatics.png", "drawings", ],
["insects.jpeg", "photography", ],
["instagramMug.jpeg", "photography", ],
["internet.jpeg", "photography", ],
["intertubes.jpeg", "photography", ],
["isolationRoom.jpeg", "photography", ],
["ivan.jpeg", "photography", ],
["iveFallen.jpeg", "photography", ],
["jaundice.jpeg", "photography", ],
["javaMonster.jpeg", "photography", ],
["jeans.jpeg", "photography", ],
["jeffEpstein.jpeg", "photography", ],
["jeffGoldblum.jpeg", "photography", ],
["jenny durkin.JPG", "uwDaily", ],
["jessyn farrell.jpg", "uwDaily", ],
["Jion.jpeg", "drawings", ],
["jokerCar.jpeg", "photography", ],
["jokerTruck.jpeg", "photography", ],
["Jonathan.jpeg", "drawings", ],
["joy.jpeg", "photography", ],
["jPopp.jpeg", "photography", ],
["justMarried.jpeg", "photography", ],
["katamari.jpeg", "photography", ],
["kek.jpeg", "photography", ],
["kidsDance.jpeg", "photography", ],
["Kim.jpeg", "paintings", ],
["Kitchen 7.PNG", "deadEnd", ],
["kittens.jpeg", "photography", ],
["kokane.jpeg", "photography", ],
["lacroix.jpeg", "photography", ],
["lawmaker.jpg", "uwDaily", ],
["laws.jpeg", "photography", ],
["Leander.jpg", "drawings", ],
["leaveRockHere.jpeg", "photography", ],
["leaves.jpg", "uwDaily", ],
["leavesConcrete.jpeg", "photography", ],
["legend.jpeg", "photography", ],
["leo.jpeg", "photography", ],
["lifeBook.jpeg", "photography", ],
["lightningMcQueen.jpeg", "photography", ],
["linux.jpeg", "photography", ],
["linuxPlane.jpeg", "photography", ],
["liveLifeInTheMeow.jpeg", "photography", ],
["Living Room 4.PNG", "deadEnd", ],
["Living Room Plant 1.PNG", "deadEnd", ],
["LivingRoom.jpeg", "drawings", ],
["loisLane.jpeg", "photography", ],
["lombard.jpeg", "photography", ],
["lordOfTheDance.jpeg", "photography", ],
["lostKitten.jpeg", "photography", ],
["love.jpeg", "photography", ],
["loveBeach.jpeg", "photography", ],
["loveFever.jpeg", "photography", ],
["lRonHubbardWay.jpeg", "photography", ],
["macaroni.jpeg", "photography", ],
["madameWeb.jpeg", "photography", ],
["Maddie1.jpeg", "drawings", ],
["Maddie2.jpeg", "drawings", ],
["MaddieAndThePancakes.jpeg", "paintings", ],
["Madhava.jpeg", "drawings", ],
["makeTheMemories.jpeg", "photography", ],
["Mango.jpeg", "paintings", ],
["maniac.jpeg", "photography", ],
["mannekin.jpeg", "photography", ],
["manRepair.jpeg", "photography", ],
["mar212003.jpeg", "photography", ],
["MasculineCollage.jpg", "miscellaneous", ],
["mattressRoof.jpeg", "photography", ],
["Maze.jpeg", "drawings", ],
["mcDonalds.jpeg", "photography", ],
["McKinley.JPG", "paintings", ],
["meanWell.jpeg", "photography", ],
["meaty.jpeg", "photography", ],
["men.jpeg", "photography", ],
["menOof.jpeg", "photography", ],
["mice.jpeg", "photography", ],
["mickey 2.jpeg", "photography", ],
["mickey.jpeg", "photography", ],
["mid.jpeg", "photography", ],
["miguels.jpeg", "photography", ],
["mimimum wage color.jpg", "uwDaily", ],
["mirror.jpeg", "photography", ],
["mirrorFall.jpeg", "photography", ],
["moisture.jpeg", "photography", ],
["mom.jpeg", "photography", ],
["monaLisa.jpeg", "photography", ],
["monitor.jpeg", "photography", ],
["monkey.JPG", "uwDaily", ],
["moth 2.jpeg", "photography", ],
["moth.jpeg", "photography", ],
["mother'sRoom.jpeg", "photography", ],
["mrBill.jpeg", "photography", ],
["myBad.jpeg", "photography", ],
["myBurrito.jpeg", "photography", ],
["mysteryMachine.jpeg", "photography", ],
["nameDate.jpeg", "photography", ],
["NaN.jpeg", "photography", ],
["nearDeath.jpeg", "photography", ],
["neighsHoarsely.jpeg", "photography", ],
["neverGiveUpBillboard.jpeg", "photography", ],
["neverGiveUpOffice.jpeg", "photography", ],
["newMexico.jpeg", "photography", ],
["nightmareMustEnd.jpeg", "photography", ],
["nlog.jpeg", "photography", ],
["no 2.jpeg", "photography", ],
["no.jpeg", "photography", ],
["noBrand.jpeg", "photography", ],
["noNoNo.jpeg", "photography", ],
["noodle.jpeg", "photography", ],
["noParking.jpeg", "photography", ],
["noRules.jpeg", "photography", ],
["noseEye.jpeg", "doodles", ],
["noSeJuega.jpeg", "photography", ],
["noTable.jpeg", "photography", ],
["noTennis.jpeg", "photography", ],
["nothingOfValue.jpeg", "photography", ],
["obamaKim.JPG", "uwDaily", ],
["obey.jpeg", "photography", ],
["observed.jpeg", "photography", ],
["OffallyGood!.jpeg", "miscellaneous", ],
["okMall.jpeg", "photography", ],
["oldLady.jpeg", "photography", ],
["Olliver.jpeg", "drawings", ],
["oneManNoPay3.jpeg", "photography", ],
["onion.jpeg", "photography", ],
["online activism.jpg", "uwDaily", ],
["ooof.jpeg", "photography", ],
["openBooks.jpeg", "photography", ],
["orangeJuiceAirport.jpeg", "photography", ],
["outBus.jpeg", "photography", ],
["outlet.jpeg", "photography", ],
["outletCeiling.jpeg", "photography", ],
["outletFaces.jpeg", "photography", ],
["outletsWeird.jpeg", "photography", ],
["outrage.jpeg", "photography", ],
["Overhead.PNG", "deadEnd", ],
["oxxxford.jpg", "uwDaily", ],
["packagedWithPride.jpeg", "photography", ],
["page.jpeg", "doodles", ],
["pain.jpeg", "photography", ],
["paintedDoor.jpeg", "photography", ],
["paintSteps.jpeg", "photography", ],
["palace.jpg", "uwDaily", ],
["pan.jpeg", "photography", ],
["panamaBeer.jpeg", "photography", ],
["panda.jpeg", "photography", ],
["pandEveryoneLovesThem.jpeg", "photography", ],
["Parents.JPG", "drawings", ],
["pasta.jpeg", "photography", ],
["pavementJoint.jpeg", "photography", ],
["peacock.jpeg", "photography", ],
["peeece.jpeg", "photography", ],
["peppers.jpeg", "photography", ],
["perms.jpeg", "photography", ],
["phucDat.jpeg", "photography", ],
["phuketThai.jpeg", "photography", ],
["pianoMelt.jpeg", "photography", ],
["pikachu.jpeg", "photography", ],
["pizz.jpeg", "photography", ],
["pizza.jpeg", "photography", ],
["pizzaBig.jpeg", "photography", ],
["pizzaMaker.jpeg", "photography", ],
["plantBox.jpeg", "photography", ],
["plantCar 2.jpeg", "photography", ],
["plantCar.jpeg", "photography", ],
["plantTruck.jpeg", "photography", ],
["plantWindow.jpeg", "photography", ],
["plantWindowBig.jpeg", "photography", ],
["playdoughFlavor.jpeg", "photography", ],
["playKitchen.jpeg", "photography", ],
["playStructure.jpeg", "photography", ],
["please.jpeg", "photography", ],
["pleaseDog.jpeg", "photography", ],
["pleaseDucks.jpeg", "photography", ],
["pointNGo.jpeg", "photography", ],
["pokemons.jpeg", "photography", ],
["Pomegranate.jpeg", "paintings", ],
["poo.jpeg", "photography", ],
["poohAndMickey.jpeg", "photography", ],
["Popcorn.jpeg", "drawings", ],
["potatoBox.jpeg", "photography", ],
["potatoTree.jpeg", "photography", ],
["powerade.jpeg", "photography", ],
["ppwp.jpeg", "photography", ],
["Prab.jpg", "drawings", ],
["pregnancy.jpg", "uwDaily", ],
["prettyTired.jpeg", "photography", ],
["primate.jpg", "uwDaily", ],
["prime.jpeg", "photography", ],
["Prohibitionist.JPG", "paintings", ],
["projecting.jpeg", "photography", ],
["pumpkin.jpg", "uwDaily", ],
["pumpkinShake.jpeg", "photography", ],
["puzzlePieces.jpeg", "photography", ],
["qrCode.jpeg", "photography", ],
["questionMark.jpeg", "photography", ],
["Rabbit.PNG", "deadEnd", ],
["rabbitsRabbitsRabbits.jpeg", "photography", ],
["RainbowHead.jpg", "paintings", ],
["rainier.jpeg", "photography", ],
["ranch.jpeg", "photography", ],
["ratings.jpg", "uwDaily", ],
["ravennaInteriors.jpeg", "photography", ],
["realEstate.jpeg", "photography", ],
["rec.jpeg", "photography", ],
["receipt.jpeg", "photography", ],
["recursion.jpeg", "photography", ],
["redTree.jpeg", "photography", ],
["refinedChineseTea.jpeg", "photography", ],
["Renaissance.JPG", "paintings", ],
["restart.jpeg", "photography", ],
["restroom.jpg", "uwDaily", ],
["rock.jpeg", "photography", ],
["roof.jpg", "drawings", ],
["rooster.jpeg", "photography", ],
["roughRoad.jpeg", "photography", ],
["roughRoadUpsideDown.jpeg", "photography", ],
["royGBiv.jpeg", "photography", ],
["rudolph.jpeg", "photography", ],
["sad.jpeg", "photography", ],
["sandwich.jpeg", "photography", ],
["Sanjay.JPG", "drawings", ],
["sassy.jpeg", "photography", ],
["sauce.jpeg", "photography", ],
["savage.jpeg", "photography", ],
["sayNoToDrugs.jpeg", "photography", ],
["Scan 1.jpeg", "doodles", ],
["Scan 12.jpeg", "doodles", ],
["Scan 13.jpeg", "doodles", ],
["Scan 14.jpeg", "doodles", ],
["Scan 15.jpeg", "doodles", ],
["Scan 16.jpeg", "doodles", ],
["Scan 17 copy.jpeg", "doodles", ],
["Scan 17.jpeg", "doodles", ],
["Scan 18.jpeg", "doodles", ],
["Scan 2.jpeg", "doodles", ],
["Scan 3.jpeg", "doodles", ],
["Scan.jpeg", "doodles", ],
["Screen Shot 2013-12-30 at 12.29.37 PM.png", "deadEnd", ],
["Screen Shot 2014-01-07 at 6.43.06 PM.png", "deadEnd", ],
["Screen Shot 2014-06-23 at 6.35.27 PM.png", "deadEnd", ],
["Screen Shot 2014-07-02 at 2.48.27 PM.png", "deadEnd", ],
["Screen Shot 2014-08-08 at 9.22.40 AM.png", "deadEnd", ],
["screenAd.jpeg", "photography", ],
["sealedAir.jpeg", "photography", ],
["securitCamera.jpeg", "photography", ],
["seenByJamesJanuch.jpeg", "photography", ],
["selectOne.jpeg", "photography", ],
["SelfPortrait.jpg", "paintings", ],
["Severance.jpg", "miscellaneous", ],
["sex ed.jpg", "uwDaily", ],
["sexyLifeSaladOn.jpeg", "photography", ],
["shaq.jpeg", "photography", ],
["Shed.png", "deadEnd", ],
["sheetMusic.jpeg", "photography", ],
["sheldon.jpeg", "photography", ],
["shitCatan.jpeg", "photography", ],
["shoeprint.jpeg", "photography", ],
["shoes.JPG", "uwDaily", ],
["shoesBasketball.jpeg", "photography", ],
["shoesClub.jpeg", "photography", ],
["shoesInBush.jpeg", "photography", ],
["shoeTracks.jpeg", "photography", ],
["shoulder.jpeg", "photography", ],
["sidepath3.png", "deadEnd", ],
["simp.jpeg", "photography", ],
["skateboardDrink.jpeg", "photography", ],
["skeletonEyes.jpeg", "photography", ],
["skibidi.jpeg", "photography", ],
["Skull.jpeg", "paintings", ],
["Skull.JPG", "drawings", ],
["SkullPainting.JPG", "paintings", ],
["smile.jpeg", "photography", ],
["smileyBoiler.jpeg", "photography", ],
["smileyBowl.jpeg", "photography", ],
["smirk.jpeg", "photography", ],
["social media.jpg", "uwDaily", ],
["sometimes.jpeg", "photography", ],
["SovietMonopoly.jpeg", "miscellaneous", ],
["spaghetti.jpeg", "photography", ],
["spaghettiL.jpeg", "photography", ],
["special.jpeg", "photography", ],
["specialFeatures.jpeg", "photography", ],
["spicy.jpeg", "photography", ],
["spiderweb.jpeg", "photography", ],
["SpinGuy.jpeg", "doodles", ],
["spyCar.jpeg", "photography", ],
["squareDance.jpeg", "photography", ],
["squirrell.jpeg", "photography", ],
["squirrellSunbathe.jpeg", "photography", ],
["squirrellTree.jpeg", "photography", ],
["squirrellUncrustable.jpeg", "photography", ],
["stair.jpeg", "photography", ],
["stairs.jpeg", "photography", ],
["Stars.jpg", "uwDaily", ],
["std.jpeg", "photography", ],
["stem.jpg", "uwDaily", ],
["stillIRise.jpeg", "photography", ],
["stop.jpeg", "photography", ],
["stopAhead.jpeg", "photography", ],
["stopp.jpeg", "photography", ],
["stopThat.jpeg", "photography", ],
["Street 1.png", "deadEnd", ],
["stress.jpeg", "photography", ],
["studyingKnowledge.jpeg", "photography", ],
["stuff.JPG", "uwDaily", ],
["subjectiveLevel.jpeg", "photography", ],
["subway.jpeg", "photography", ],
["subwayTouchscreen.jpeg", "photography", ],
["succ.jpeg", "photography", ],
["Suey.png", "miscellaneous", ],
["summer.jpg", "uwDaily", ],
["Sunflowers.JPG", "drawings", ],
["Sunland.jpeg", "drawings", ],
["suprome.JPG", "photography", ],
["tabasco.jpeg", "photography", ],
["tacoBell.jpeg", "photography", ],
["Taft.JPG", "paintings", ],
["taiwam.jpeg", "photography", ],
["Teapots.png", "miscellaneous", ],
["tech love bw.jpg", "uwDaily", ],
["tech vs nature.jpg", "uwDaily", ],
["Teddy.PNG", "miscellaneous", ],
["telephon.jpeg", "photography", ],
["Tessellation.jpg", "drawings", ],
["texasMan.jpeg", "photography", ],
["thatDarnCat.jpeg", "photography", ],
["TheActualBeachBoys.jpeg", "miscellaneous", ],
["theBeachBoysByTheBeachBoys.jpeg", "photography", ],
["TheodoreRoosevelt.JPG", "paintings", ],
["ThiccSpaghetti.jpg", "miscellaneous", ],
["thisIsMorgan.jpeg", "photography", ],
["thisworks.jpeg", "photography", ],
["thoughts.jpg", "uwDaily", ],
["throopSt.jpeg", "photography", ],
["thumbsUpGlove.jpeg", "photography", ],
["tires.jpeg", "photography", ],
["tissueGlass.jpeg", "photography", ],
["TitleScreen.jpg", "lifeOfPika", "1", ],
["to the bone.jpg", "uwDaily", ],
["toaster.jpeg", "photography", ],
["toiletGlow.jpeg", "photography", ],
["toiletLeaves.jpeg", "photography", ],
["toiletPaperFlush.jpeg", "photography", ],
["toilets.jpeg", "photography", ],
["towers.jpeg", "photography", ],
["trafficCone.jpeg", "photography", ],
["trafficConeSideways.jpeg", "photography", ],
["trainNotFound.jpeg", "photography", ],
["TrainParking.jpeg", "miscellaneous", ],
["trainWindows.jpeg", "photography", ],
["tramTickets.jpeg", "photography", ],
["trash.jpeg", "photography", ],
["trashCan.jpeg", "photography", ],
["treeBowl.jpeg", "photography", ],
["treeCar.jpeg", "photography", ],
["treeCaution.jpeg", "photography", ],
["treeHand.jpeg", "photography", ],
["treePublicNotice.JPG", "photography", ],
["trees.jpeg", "photography", ],
["treeSign.jpeg", "photography", ],
["treeWilt.jpeg", "photography", ],
["trendingNews.jpeg", "photography", ],
["Trotsky.jpeg", "drawings", ],
["truckBroken.jpeg", "photography", ],
["trump.jpg", "uwDaily", ],
["trumpers.jpg", "uwDaily", ],
["tshirt.jpeg", "photography", ],
["tunnel.jpeg", "photography", ],
["tv.jpeg", "photography", ],
["ucsf.jpeg", "photography", ],
["unitedStatesOfAmerica.jpeg", "photography", ],
["unixError.jpeg", "photography", ],
["upperDoor.jpeg", "photography", ],
["vag.jpeg", "photography", ],
["vaporwave.jpeg", "photography", ],
["veganDog.jpeg", "photography", ],
["vegetables.jpg", "uwDaily", ],
["veggies.jpeg", "photography", ],
["vets.jpg", "uwDaily", ],
["voteNo.jpeg", "photography", ],
["Vulture.jpeg", "paintings", ],
["waffles.jpeg", "photography", ],
["wangSteak.jpeg", "photography", ],
["warningCancer.jpeg", "photography", ],
["washingtonFederal.jpeg", "photography", ],
["washMyHandsB4IPiss.jpeg", "photography", ],
["watchOutForPinching.jpeg", "photography", ],
["Waterbottle.jpeg", "drawings", ],
["weAre40.jpeg", "photography", ],
["wedding.jpeg", "photography", ],
["wetCement.jpeg", "photography", ],
["wetPuddy.jpg", "photography", ],
["whatever.jpeg", "photography", ],
["whatIsThis.jpeg", "photography", ],
["whatYearWereYouBorn.jpeg", "photography", ],
["whereAmI.jpeg", "photography", ],
["whoGivesACrap.jpeg", "photography", ],
["whyAreYouReportingThis.jpeg", "photography", ],
["whyTry.jpg", "photography", ],
["wig.jpeg", "photography", ],
["window.jpeg", "photography", ],
["Window.jpg", "drawings", ],
["windowGirl.jpeg", "photography", ],
["windowSideways.jpeg", "photography", ],
["WineAndOnion.jpg", "paintings", ],
["Winston.jpeg", "paintings", ],
["wizard.jpeg", "photography", ],
["wolf 1.jpeg", "miscellaneous", ],
["wolf2.jpeg", "miscellaneous", ],
["WolfOfWallStreetVHS.jpeg", "miscellaneous", ],
["women in stem 2.jpg", "uwDaily", ],
["wow.jpeg", "photography", ],
["Yard 5.PNG", "deadEnd", ],
["yo.jpeg", "photography", ],
["yogurtCheeseAndBeer.jpeg", "photography", ],
["yoMama.jpeg", "photography", ],
["youAreMomGayLol.jpeg", "photography", ],
["youAreYourId.jpeg", "photography", ],
["zebraMural.jpeg", "photography", ],
["zombies.jpeg", "photography", ],
["zza.jpeg", "photography", ],
["WitchettyGrub.jpg", "paintings", ],
["TheCrabbzler.jpeg", "miscellaneous", ],
]