let oneLiners = [
"Do you prefer pencils or pens?\nDa pens",
"Ruffles: ridged for her pleasure?",
"Ask not for whom the Taco Bell tolls, it tolls for thee",
"Young Sheldon should’ve been called Little Bang Theory",
"Bella Hadid WHAT?",
"I’m-a from-a the FBI, the Federal Bureau of Italians",
"I don’t give a hoot about owls",
"Being illiterate is like seeing a paywall on everything",
"What if kink shaming is my kink",
"My pronouns are us/them",
// "There’s no I in cum, but there is cum in my eye",
"Quentin Tarantino means no",
"Leann Rimes? No it doesn’t ",
"Paul McCarney: Beatle alcohol syndrome?",
"Object permanence more like object impermanence",
"Stockholm syndrome more stuck home syndrome",
"Las Vegas? More like Loss Vegas",
"Happy hour? More like sad hour",
"Le miz? More like is lame",
"Israel? More like isn’t real",
"Edibles? More like inedibles",
"Biceps? More like hello-ceps",
"Stranger things? More like things are strange",
"Why is it so bad to hate crime?",
"I’ve got to see a horse about a man",
"If I tell a joke, and nobody laughs, was it actually funny? ",
"This changes everything… OR DOES IT?",
"Let the commencement… commence",
"I tried to take Binary 101, turns out it was 5th in the series",
"Harder done than said",
"Prideth come before the falleth",
"I'm a twenty nothing",
"You always cease to amaze",
"Food is in the mouth of the beholder",
"Populist in the streets, fascist in the sheets",
"To do: write to do list",
"I pity the foo fighters",
"This knife isn't cutting it",
"Absolute power absolutely corrupts absolutely",
"This has got to be either the best hamburger or the worst souffle I've ever had",
"Real men don’t subscribe to gender roles",
"Bill Nerson the science person",
"You put the IRL in girl",
"Whose dick do I gotta suck to suck a dick around here?",
"God makes plans, man laughs",
"No capital pains, no capital gains",
"We are in agreeance that ‘agreeance’ is not a word",
"It’s not just amazing, it’s the mazing!",
//"Now that's an ass I could get behind",
"Jackson 5 more like Jackson 4",

//"Rim Job? more like grim job",
"I can cry on demand:\n“ON DEMAND!\”",
"It was so hot out, I went to a sauna to cool down",
"I never repeat myself. I NEVER repeat myself.",
"To each Charlize Theron",
"#DespicableMeTooMovement",
"Carpe dayum!",
"Taj your own Hal!",
"No, YOU goslavia",
"If it's any constellation... the big dipper",
"It's not my fault, it's San Andreas fault"
]