let drawingsList = [
"Artichoke.JPG",
"CherryTree.jpg",
"Fountain.jpg",
"Leander.jpg",
"LivingRoom.JPG",
"Maddie1.jpeg",
"Maddie2.jpeg",
"Madhava.jpeg",
"Parents.JPG",
"Popcorn.JPG",
"Prab.jpg",
"Sanjay.JPG",
"Skull.JPG",
"Sunflowers.JPG"]