let miscellaneousList = [
"100 Degrees.mp3",
"420 Loop.mp3",
"Chill Loop.mp3",
"Country Tuff.mp3",
"Highjam.mp3",
"Joe Frank.wav",
"Jordan.mp3",
"Jungleloop.mp3",
"Loooop.mp3",
"Nirvana Loop.mp3",
"Quant Drum Loop.mp3",
"Roach.mp3",
"Round Black Glasses.mp3",
"Space Jam.mp3",
"Spaghettiloop.mp3",
"Spheres in Perspective.wav",
"Surfin'.mp3",
"Template.mp3"]