let allSongs = [
"Breckenridge",
"Joanie Dance",
"Joanie",
"Guess You Had To Be There",
"Cats",
"Woke Up",
"Free",
"Spaghetti",
"Beetle",
"Maddie",
"Take Me Out Techno",
"Crypt",
"Jinx",
"Writing's On The Wall",
"Jungleloop",
"One Love",
"For You",
"Rainy Days Shorter",
"Round And Around",
"I Promise",
"Day Song",
"Simple Song",
"Another World",
"Daisy",
"Take Me Out",
"Like A Star",
"Terrestrial Beauty",
"Wasting",
"Take You With Me",
"Warming Up",
"Buzzards",
"Take a Picture",
"Don't Get Me Down",
"Bandsong",
"Walking in the Dark",
"Oh My Darling",
"Golden Gate",
"True Crime",
"Capeman",
"In My Bones",
"Rising Sun",
"Oh Baby",
"Music Flows Through Me",
"Burn",
"It's Hard To Write A Song On A Guitar",
"Take Two",
"Tightrope",
"Falling",
"I'll Go",
"Drive On",
"Classic Chorus",
"High Art",
"I Found Out",
"Inner Shell",
"Motorcycle",
"Why Did You Have To Do It",
"Cha Cha",
"Watermelon",
"Hangin' On",
"Blue Water",
"Keep Down",
"Gettin Over It",
"Feel Like a Fraud",
"Happened By Now",
"Miyazaki Movies",
"I Didn't Know",
"Runaround Kid",
"Touch My Neck",
"Bad Dog",
"Falling Down",
"Run Away Natalia",
"Crumb",
"Way Back",
"West Fandango",
"Bad Intentions",
"Electric",
"Ojie",
"Where Do We Go",
"Workin So Hard",
"Walkalong",
"Johnny",
"Advocating",
"Tadpoles",
"Leo",
"High School",
"Scary Door",
"Breakfast on the Shore",
"Surf Song",
"I Have Gone Away",
"Weekend",
"Army",
"Soul is Tired",
"Lonely Heart",
"Coming to a Close",
"Left Out",
"Desiree",
"Oceany Song",
"Miso",
"Little Spider",
"Rest Up",
"Once Upon A Time",
"Drunk",
"Let's Go Down",
"Embarrassed",
"Sweet Little Bird",
"Summery Morning",
"Walk Along",
"Great American",
"Stuck in a Loop",
"Fall Farther",
"Mean Old Man",
"Joe Frank",
]