let songTable = [
["***TITLE", "***EXTENSION", "***KEY", "***TRACK", "***GROUP", "***YOUTUBE", "***CHORDS", "***IMAGE", ],
["100 Degrees", "mp3", "", "", "instrumentals", ],
["420 Loop", "mp3", "", "", "instrumentals", ],
["A Brief History of Galvanism", "m4a", "", "", "rebeccasAnimations", "A312PsGlMTk", ],
["Action Park Theme", "m4a", "", "", "oldPiano", ],
["Angry Gershwin", "m4a", "", "", "oldPiano", ],
["Assignment 2", "wav", "", "1", "dxarts", ],
["Assignment 3", "wav", "", "2", "dxarts", ],
["Based On", "wav", "", "", "podcasts", ],
["Beetle", "mp3", "beetle", "", "songs", "Zk6Q6SfcGYU", "1", ],
["Bingo's Fantastic Journey", "m4a", "", "", "rebeccasAnimations", "in3JswOAFDw", ],
["Bond", "m4a", "", "", "oldPiano", ],
["Bond Theme", "m4a", "", "", "oldPiano", ],
["Bouncy Classical", "m4a", "", "", "oldPiano", ],
["California", "wav", "", "", "mashups", "aqviXXbtiUg", ],
["Child Death Lullabye", "m4a", "", "", "oldPiano", ],
["Chill Loop", "mp3", "", "", "instrumentals", ],
["Choir Intro (Sadly Bad)", "m4a", "", "", "oldPiano", ],
["Classic Songbook", "m4a", "", "", "oldPiano", ],
["Country", "mp3", "", "", "instrumentals", ],
["Disco", "mp3", "", "", "mashups", ],
["Don't Bring Me Diamonds", "mp3", "", "", "mashups", "bbd8sI2k7fk", ],
["Dream a Little Dream of God", "mp3", "", "", "mashups", "emlw9bLSbcA", ],
["Drew's Blues: A Rock Operetta", "mp3", "drew", "", "musicals", "NzcUOxN2IuM", ],
["Etude 4", "m4a", "", "", "oldPiano", ],
["Falling Noir", "m4a", "", "", "oldPiano", ],
["Final", "wav", "", "9", "dxarts", ],
["Foggy Polychords", "m4a", "", "", "oldPiano", ],
["Forgotten Escape", "m4a", "", "", "oldPiano", ],
["Freedom Party", "m4a", "", "", "oldPiano", ],
["Friend Death", "m4a", "", "", "oldPiano", ],
["Frog Chase", "wav", "", "", "rebeccasAnimations", "7s0P97t_Xbg", ],
["Fun Fun Fun Fun Fun Fun Fun", "", "", "", "mashups", "AurwJd0zw0I", ],
["Griven Credits", "mp3", "", "6", "griven", ],
["Griven Epilogue", "mp3", "", "7", "griven", ],
["Griven Menu", "mp3", "", "1", "griven", ],
["Griven Opening", "mp3", "", "2", "griven", ],
["Griven Pool", "mp3", "", "3", "griven", ],
["Griven Room", "mp3", "", "5", "griven", ],
["Griven Walkthrough", "mp3", "", "4", "griven", ],
["High Jam", "mp3", "", "", "instrumentals", ],
["Hymn to Nikkal", "m4a", "", "", "oldPiano", ],
["I-IV-V", "mp3", "", "", "mashups", ],
["Inspiring Musical", "m4a", "", "", "oldPiano", ],
["Japanese Dream Journey", "mp3", "", "", "oldPiano", ],
["Joe Frank", "wav", "", "", "instrumentals", ],
["Jordan", "mp3", "", "", "instrumentals", ],
["Jungleloop", "mp3", "", "", "instrumentals", ],
["Lab 3", "wav", "", "3", "dxarts", ],
["Lab 4", "wav", "", "4", "dxarts", ],
["Lab 5", "wav", "", "5", "dxarts", ],
["Lab 6", "wav", "", "6", "dxarts", ],
["Lab 7", "wav", "", "7", "dxarts", ],
["Looooop", "mp3", "", "", "instrumentals", ],
["Maloy's Jewelry Workshop", "mp3", "", "", "rebeccasAnimations", "8m9JRKYb5Ho", ],
["Midterm", "wav", "", "8", "dxarts", ],
["Mountains at Last", "mp3", "", "", "mashups", "1ioAXzjOMWU", ],
["Nighttime Barnyard", "mp3", "", "", "oldPiano", ],
["Nirvana Loop", "mp3", "", "", "instrumentals", ],
["Old Clockwork", "m4a", "", "", "oldPiano", ],
["Old Dissonance", "m4a", "", "", "oldPiano", ],
["One Impala", "mp3", "", "", "mashups", "Z2dzon0iNFo", ],
["Pee-Wee Romp", "m4a", "", "", "oldPiano", ],
["Quant Drum Loop", "mp3", "", "", "instrumentals", ],
["Roach", "mp3", "", "", "instrumentals", ],
["Round Black Glasses", "mp3", "", "", "instrumentals", ],
["Russian Lullabye", "m4a", "", "", "oldPiano", ],
["Russian Organ", "mp3", "", "", "oldPiano", ],
["Scary Western", "m4a", "", "", "oldPiano", ],
["Seattle Birthday", "m4a", "", "", "oldPiano", ],
["Space Jam", "mp3", "", "", "instrumentals", ],
["Spaghetti Loop", "mp3", "", "", "instrumentals", ],
["Spheres in Perspective", "wav", "", "", "instrumentals", ],
["Surfin'", "mp3", "", "", "instrumentals", ],
["Template", "mp3", "", "", "instrumentals", ],
["The Ballad of Luigi", "mp3", "luigi", "", "songs", "-yIAxvgeHmE", "1", ],
["The Blue Gecko", "m4a", "", "", "rebeccasAnimations", "DRHOmGiXeqs", ],
["The Civil Experiment", "wav", "", "", "podcasts", ],
["The Summer Dragons", "mp3", "", "", "rebeccasAnimations", "7wnEuywiGb4", ],
["Train", "m4a", "", "", "oldPiano", ],
["Unalike Lover's Musical Number", "m4a", "", "", "oldPiano", ],
["Urban Beat", "m4a", "", "", "oldPiano", ],
["Users", "mp3", "", "", "podcasts", ],
["Wandering C", "m4a", "", "", "oldPiano", ],
["Western 20's", "m4a", "", "", "oldPiano", ],
["Western Mafia", "m4a", "", "", "oldPiano", ],
]