let topBouncesList = [
".DS_Store",
"0-list.js",
"A Little Too High.mp3",
"Absolved.mp3",
"Advocating.mp3",
"Alligator Swamp.mp3",
"Although.mp3",
"Arena.mp3",
"Army.mp3",
"Bad Dog.mp3",
"Bad Intentions.mp3",
"Beetle the Cat.mp3",
"Besides Me.mp3",
"Big Adventure.mp3",
"Blood in the Water.mp3",
"Blue Water.mp3",
"Breakfast on the Shore.mp3",
"Breckenridge.mp3",
"Burn.mp3",
"Buzzards.mp3",
"Capeman.mp3",
"Cats.mp3",
"Cha Cha.mp3",
"Classic Chorus.mp3",
"Come Dream With Me.mp3",
"Coming to a Close.mp3",
"Crumb.mp3",
"Crypt.mp3",
"Daisy.mp3",
"Dark and Cold.mp3",
"Day Song.mp3",
"Days with Him.mp3",
"Deli Song.mp3",
"Desiree.mp3",
"Disjointed.mp3",
"Don't Get Me Down.mp3",
"Don't Go Near the Edge.mp3",
"Don't Let Go (Power Riff).mp3",
"Downtempo.mp3",
"Drive On.mp3",
"Drown.mp3",
"Embarrassed.mp3",
"Fade Out.mp3",
"Fall Farther.mp3",
"Feel Like a Fraud.mp3",
"Feelin Like Shit.mp3",
"Fly Fly Around.mp3",
"Follow.mp3",
"For You.mp3",
"Free Your Mind.mp3",
"Gettin Over It.mp3",
"Go Around.mp3",
"Golden Gate.mp3",
"Good Time to Go.mp3",
"Great American.mp3",
"Guess You Had to Be There.mp3",
"Hangin' On.mp3",
"Happened By Now.mp3",
"Hard to Get Around.mp3",
"Hello Now.mp3",
"High Art.mp3",
"High School.mp3",
"Hum.mp3",
"I Found Out.mp3",
"I Promise.mp3",
"I'm Fine.mp3",
"In My Bones.mp3",
"Inner Shell.mp3",
"Its Hard To Write A Song On A Guitar.mp3",
"Jinx.mp3",
"Joanie.mp3",
"Joe Frank.mp3",
"Johnny.mp3",
"Keep Down.mp3",
"Lay Down.mp3",
"Let's Go Down.mp3",
"Like a Dog.mp3",
"Like a Star.mp3",
"Little Spider.mp3",
"Lonely Boy.mp3",
"Lonely Heart.mp3",
"Love Conquers All.mp3",
"Maddie.mp3",
"Mary S. Young Park.mp3",
"Matt Lauer.mp3",
"McCartney-esque.mp3",
"Mean Old Man.mp3",
"Miss You When You Go.mp3",
"Miyazaki Movies.mp3",
"Motorcycle.mp3",
"Music Flows Through Me.mp3",
"Now and Then.mp3",
"Oceany Song.mp3",
"Off Track.mp3",
"Oh Baby.mp3",
"Ojie.mp3",
"Old Friend.mp3",
"Once Upon a Time.mp3",
"One Love.mp3",
"Paint a Picture.mp3",
"Play the Game.mp3",
"Rainy Days Shorter.mp3",
"Rising Sun.mp3",
"Round and Around.mp3",
"Run Away Natalia.mp3",
"Run the World.mp3",
"Runaround Kid.mp3",
"Runaway.mp3",
"Scary Door.mp3",
"Simple Song.mp3",
"Slo Mo.mp3",
"Soul is Tired.mp3",
"Spaghetti Forever.mp3",
"Stuck in a Loop.mp3",
"Summery Morning.mp3",
"Surf Song.mp3",
"Sweet Little Bird.mp3",
"Take Me Out.mp3",
"Take You With Me.mp3",
"Take it Slow.mp3",
"Terrestrial Beauty.mp3",
"The Ballad of Luigi.mp3",
"Tightrope.mp3",
"Touch My Neck.mp3",
"Trenchcoat.mp3",
"Walk Home.mp3",
"Walkalong.mp3",
"Walking in the Dark.mp3",
"Warming Up.mp3",
"Wasted.mp3",
"Wasting.mp3",
"Watermelon.mp3",
"Way Back.mp3",
"We Will Be Taking Over.mp3",
"Weekend.mp3",
"When I'm Gone.mp3",
"Where Are We Now.mp3",
"Where Did She Go.mp3",
"Where Do We Go.mp3",
"Why Did You Have To Do It.mp3",
"Woke Up.mp3",
"Wordless.mp3",
"Workin So Hard.mp3",
"Writing's on the Wall.mp3",
]
